on:
  push:
  pull_request:

name: 'check-code-with-shellcheck'

jobs:
  shellcheck:
    name: will status be green? :)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
