on:
  push:
    branches-ignore:
      - 'autocommit'

name: 'check-code-with-shellcheck'

jobs:
  shellcheck:
    name: Github Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run Shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
      env:
        SHELLCHECK_OPTS: -e SC2059 -e SC2034
